services:
  - type: web
    name: teachermeet-signaling
    runtime: node
    plan: free
    rootDir: teacher-meet-app/signaling-server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: teachermeet-web-client
    runtime: static
    rootDir: teacher-meet-app/web-client
    buildCommand: ""
    staticPublishPath: .